import type { Metadata } from 'next';
import localFont from 'next/font/local';
import ThemeProvider from './theme-provider';
import './globals.css';
import Links from '@/app/links';

export const runtime = 'edge';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // console.log(
  //   'Layout - meant to be Static Server Component (not render at request time)',
  // );

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col flex-wrap justify-center items-center">
          <time
            dateTime={new Date().toLocaleTimeString()}
            suppressHydrationWarning
          >
            {new Date().toLocaleTimeString()}
          </time>

          <h1 className="mt-2 text-pretty text-4xl font-semibold tracking-tight text-gray-900 sm:text-3xl mb-3">
            Choose which type of rendering you want to try out
          </h1>

          <Links />

          <ThemeProvider>{children}</ThemeProvider>
        </div>
      </body>
    </html>
  );
}
