import type { Metadata } from 'next';
import localFont from 'next/font/local';
import ThemeProvider from './theme-provider';
import './globals.css';
import Links from '@/app/links';
import { createPostLoggerRequest, TEST_HEADER_NAME } from 'send-headers';
import { getOptionalRequestContext } from '@cloudflare/next-on-pages';

export const runtime = 'edge';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function getRequestContextSafely() {
  try {
    return getOptionalRequestContext();
  } catch (error) {
    const phase =
      typeof process !== 'undefined' ? process.env.NEXT_PHASE : undefined;
    if (phase !== 'phase-production-build') {
      console.warn(
        'Cloudflare request context not available; skipping POST logger bindings',
        error,
      );
    }
    return undefined;
  }
}

async function sendPostLoggerRequest() {
  const phase =
    typeof process !== 'undefined' ? process.env.NEXT_PHASE : undefined;
  if (phase === 'phase-production-build') {
    return;
  }

  const context = getRequestContextSafely();
  const processEndpoint =
    typeof process !== 'undefined' ? process.env.POST_LOGGER_ENDPOINT : undefined;
  const endpoint = context?.env?.POST_LOGGER_ENDPOINT ?? processEndpoint;

  try {
    const request = createPostLoggerRequest({ url: endpoint });
    const response = await fetch(request);

    if (!response.ok) {
      console.warn(
        `POST logger responded with status ${response.status}`,
        await response.text().catch(() => ''),
      );
    } else {
      console.log(`Sent POST logger request with ${TEST_HEADER_NAME} header`);
    }
  } catch (error) {
    console.warn('Failed to contact POST logger server', error);
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log(
    'Layout - meant to be Static Server Component (not render at request time)',
  );

  await sendPostLoggerRequest();

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col flex-wrap justify-center items-center">
          <time
            dateTime={new Date().toLocaleTimeString()}
            suppressHydrationWarning
          >
            {new Date().toLocaleTimeString()}
          </time>

          <h1 className="mt-2 text-pretty text-4xl font-semibold tracking-tight text-gray-900 sm:text-3xl mb-3">
            Choose which type of rendering you want to try out
          </h1>

          <Links />

          <ThemeProvider>{children}</ThemeProvider>
        </div>
      </body>
    </html>
  );
}
